### ISSUE TITLE
UnicodeDecodeError when sending a request

### ISSUE THREAD

**Issue by fishy15** [prologin/camisole#51]
Hello,

When trying to set up camisole onto a computer running Ubuntu Server 20.04, I used the instructions [on the documentation page](https://camisole.prologin.org/installation.html#manual-install) for manual installation. I got through all of the steps, but when I run `camisole test` or try to send the request given in the README, I get a UnicodeDecodeError. Specifically, I get: 

```
Traceback (most recent call last):
  File "/usr/local/bin/camisole", line 11, in <module>
    load_entry_point('camisole==1.4', 'console_scripts', 'camisole')()
  File "/usr/local/lib/python3.8/dist-packages/camisole-1.4-py3.8.egg/camisole/__main__.py", line 54, in main
  File "/usr/local/lib/python3.8/dist-packages/camisole-1.4-py3.8.egg/camisole/progs/test.py", line 12, in handle
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/camisole-1.4-py3.8.egg/camisole/progs/languages.py", line 24, in print_working_languages
  File "/usr/local/lib/python3.8/dist-packages/camisole-1.4-py3.8.egg/camisole/ref.py", line 8, in test
  File "/usr/local/lib/python3.8/dist-packages/camisole-1.4-py3.8.egg/camisole/models.py", line 212, in run
  File "/usr/local/lib/python3.8/dist-packages/camisole-1.4-py3.8.egg/camisole/models.py", line 181, in run_compilation
  File "/usr/local/lib/python3.8/dist-packages/camisole-1.4-py3.8.egg/camisole/models.py", line 144, in compile
  File "/usr/local/lib/python3.8/dist-packages/camisole-1.4-py3.8.egg/camisole/isolate.py", line 100, in __aenter__
  File "/usr/local/lib/python3.8/dist-packages/camisole-1.4-py3.8.egg/camisole/utils.py", line 95, in __get__
  File "/usr/local/lib/python3.8/dist-packages/camisole-1.4-py3.8.egg/camisole/isolate.py", line 239, in isolate_conf
  File "/usr/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.8/configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/local/lib/python3.8/dist-packages/camisole-1.4-py3.8.egg/camisole/isolate.py", line 237, in dummy_section
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 96: invalid continuation byte
```

I've tried deleting the binary that running the installation creates and reinstalling camisole, but this doesn't seem to have fixed anything. Why is this happening?

**Comment by lportemo** [comment]
Hello, have you encountered an error (even non-blocking) during the `python3 setup.py install` step ?

**Comment by fishy15** [comment]
It doesn't look like there are any errors when running the installation script. The value for `$LANG` is `C.UTF-8`

**Comment by fishy15** [comment]
Ah sorry, after returning back to work on this, it turns out that this was an issue with how I configured isolate.

**Comment by lportemo** [comment]
No problem :) good luck with camisole
